### ISSUE TITLE
Error while changing a user's password

### ISSUE THREAD

**Issue by matt-boris** [mozilla-services/pulseguardian#430]
```bash
Unknown error occurred.

Rabbit URL: https://pulse.mozilla.org/api/
Rabbit user: <user>
Error:
Traceback (most recent call last):
  File "/app/pulseguardian/guardian.py", line 408, in guard
    bindings = pulse_management.bindings(vhost=config.rabbit_vhost)
  File "/app/pulseguardian/management.py", line 87, in bindings
    return [b for b in bindings if b["source"]]
  File "/app/pulseguardian/management.py", line 87, in <listcomp>
    return [b for b in bindings if b["source"]]
TypeError: string indices must be integers
```

**Comment by matt-boris** [comment]
Can no longer reproduce this.
