### ISSUE TITLE
Auth0 login is not working

### ISSUE THREAD

**Issue by marco-c** [mozilla-services/pulseguardian#59]
When I try to login, I get an "Internal Server Error".

**Comment by edmorley** [comment]
I get an HTTP 500 too. In papertrail:

```
WARNING:oic.utils.keyio:Wrong Content_type 
ERROR:oic.oauth2.message:Issuer "<REDACTED>" not in keyjar 
[2018-02-16 10:42:22,223] ERROR in app: Exception on /redirect_uri [GET] 
Traceback (most recent call last): 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request 
    rv = self.handle_user_exception(e) 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception 
    reraise(exc_type, exc_value, tb) 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request 
    rv = self.dispatch_request() 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request 
    return self.view_functions[rule.endpoint](**req.view_args) 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 97, in _handle_authentication_response 
    userinfo = self._do_userinfo_request(authn_resp['state'], self.userinfo_endpoint_method) 
  File "/app/.heroku/python/lib/python2.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 115, in _do_userinfo_request 
    return self.client.do_user_info_request(method=userinfo_endpoint_method, state=state) 
  File "/app/.heroku/python/lib/python2.7/site-packages/oic/oic/__init__.py", line 896, in do_user_info_request 
    res = _schema().from_json(txt=_txt) 
  File "/app/.heroku/python/lib/python2.7/site-packages/oic/oauth2/message.py", line 480, in from_json 
    return self.from_dict(json.loads(txt)) 
  File "/app/.heroku/python/lib/python2.7/site-packages/oic/oauth2/message.py", line 375, in from_dict 
    self._add_value(skey, vtyp, key, val, _deser, null_allowed) 
  File "/app/.heroku/python/lib/python2.7/site-packages/oic/oauth2/message.py", line 454, in _add_value 
    skey)) 
ValueError: "2018-02-16T10:42:20.819Z", wrong type of value for "updated_at" 
```

**Comment by markrcote** [comment]
Looks like our fork of Flask-pyoidc requires oic 0.9.1.0: https://github.com/mozilla-iam/Flask-pyoidc/blob/master/setup.py#L14

I downgraded oic and redeployed; marco confirmed that it is working again.

**Comment by edmorley** [comment]
I would recommend adding `pip check` to the Travis job, since that validates all version constraints are met (needs pip 9+ iirc). Why pip doesn't do so by default is beyond me (though think the plan is to do so in the future).

**Comment by jgehrcke** [comment]
For the record: Auth0 will enhance compatibility for you, if you ask them. See Auth0's response to my inquiry here: https://community.auth0.com/t/oidc-id-token-claim-updated-at-violates-oidc-specification-breaks-rp-implementations/24098
